pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/OnBoardingPart3/testing-strategy-3"
        WEB_PATH="${env.JENKINS_HOME}/workspace/OnBoardingPart3/testing-strategy-3/web"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        E2E_PATH="${PROJECT_PATH}/e2e-web"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
        REPORT_DIR="${env.PROJECT_PATH}/e2e-web/cypress/cucumber-json"
    }

    stages {
        stage('Build') {
           steps {
                dir("${WEB_PATH}") {
                    sh """
                    echo "Build"
                    npm i && npm run start &
                    """
                }
            }
        }
        stage('Test environment DEV') {
            steps {
                dir("${E2E_PATH}") {
                    sh """
                    echo "Test"
                    npm run test
                    npm run generate-report
                    """
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: '${REPORT_DIR}', reportFiles: 'index.html', reportName: 'Cypress HTML Report', reportTitles: '', useWrapperFileDirectly: true])
                }
        }
        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Deployment"
                    """
                }
            }
        }
    }
    post {
        always {
            dir("${SCRIPTS_PATH}") {
                sh """
                ./application-management.sh close
                """
            }
        }
    }
}